# Generated by Django 2.0 on 2018-01-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('author_avatar', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('like', models.CharField(max_length=255)),
            ],
        ),
    ]
